#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=7

# Secrets never touch the repo: the captured values live under ~/.config, and
# only the non-secret ones (team id, key id, issuer id) are persisted at all.
ENV_FILE="$HOME/.config/lumeshot/signing.env"
WORK="$HOME/.config/lumeshot/signing-work"
mkdir -p "$(dirname "$ENV_FILE")" "$WORK"
chmod 700 "$(dirname "$ENV_FILE")" "$WORK"
touch "$ENV_FILE"; chmod 600 "$ENV_FILE"

# base64 -w0 is GNU; macOS base64 has no -w and never wraps by default.
b64() {
  if base64 --help 2>&1 | grep -q -- '-w'; then base64 -w0 "$1"; else base64 "$1" | tr -d '\n'; fi
}

banner "Lumeshot Developer ID signing + notarization"

# ──────────────────────────────────────────────────────────────────────────
stage "Prerequisites"
say "This sets up the six GitHub secrets that .github/workflows/release.yml"
say "needs to sign and notarize a release dmg."
printf '\n'
MISSING=0
for tool in openssl curl gh; do
  if command -v "$tool" >/dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$tool"
  else
    printf '  %s✗ %s (required)%s\n' "$RED" "$tool" "$RESET"; MISSING=1
  fi
done
if gh auth status >/dev/null 2>&1; then
  printf '  %s✓%s gh authenticated → %s\n' "$GREEN" "$RESET" "$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || echo 'unknown repo')"
else
  printf '  %s✗ gh is not authenticated — run: gh auth login%s\n' "$RED" "$RESET"; MISSING=1
fi
printf '\n'
[ "$MISSING" -eq 0 ] || { warn "install/authenticate the above, then re-run."; exit 1; }
note "You need the Account Holder role in your Apple Developer team to create"
note "a Developer ID certificate. Admin alone is not enough."
pause "Ready?"

# ──────────────────────────────────────────────────────────────────────────
stage "Apple Team ID"
say "Your 10-character Team ID identifies which team signs the app."
open_url "https://developer.apple.com/account#MembershipDetailsCard"
step "Sign in, then find 'Team ID' under Membership Details."
ask TEAM_ID "Paste your Team ID (e.g. A1B2C3D4E5):"
if ! printf '%s' "$TEAM_ID" | grep -qE '^[A-Z0-9]{10}$'; then
  warn "That does not look like a 10-character Team ID; continuing anyway."
fi
ask APPLE_EMAIL "Paste the Apple ID email for this account:"
write_env TEAM_ID "$TEAM_ID"
write_env APPLE_EMAIL "$APPLE_EMAIL"
set_secret TEAM_ID "$TEAM_ID"

# ──────────────────────────────────────────────────────────────────────────
stage "Generate a signing key and CSR"
say "Apple issues a certificate against a Certificate Signing Request. Keychain"
say "Access is the usual way to make one, but openssl does it on any machine —"
say "which matters here, since the private key must end up in a .p12 anyway."
printf '\n'
if [ -f "$WORK/developer-id.key" ] && ! confirm "A private key already exists. Generate a NEW one (invalidates any cert issued against the old one)?"; then
  note "Keeping the existing key at $WORK/developer-id.key"
else
  openssl req -new -newkey rsa:2048 -nodes \
    -keyout "$WORK/developer-id.key" \
    -out "$WORK/developer-id.csr" \
    -subj "/emailAddress=$APPLE_EMAIL/CN=Lumeshot Developer ID/C=US" 2>/dev/null
  chmod 600 "$WORK/developer-id.key"
  printf '  %s✓%s wrote %s\n' "$GREEN" "$RESET" "$WORK/developer-id.csr"
fi
note "Private key: $WORK/developer-id.key (never leaves this machine except as the .p12)"
pause

# ──────────────────────────────────────────────────────────────────────────
stage "Create the Developer ID Application certificate"
open_url "https://developer.apple.com/account/resources/certificates/add"
step "Choose 'Developer ID Application' (NOT 'Developer ID Installer')."
step "If asked about a profile type, pick the default (G2 Sub-CA)."
step "Upload this CSR file:"
printf '\n      %s%s%s\n\n' "$BOLD" "$WORK/developer-id.csr" "$RESET"
step "Click Continue, then Download. You'll get a developerID_application.cer."
note "Apple caps you at 5 Developer ID Application certificates per team, and"
note "they cannot be deleted — only revoked. Reuse one if you already have it."
printf '\n'
ask CER_PATH "Full path to the downloaded .cer:"
CER_PATH="${CER_PATH/#\~/$HOME}"
[ -f "$CER_PATH" ] || { warn "No file at $CER_PATH"; exit 1; }
if ! openssl x509 -inform DER -in "$CER_PATH" -noout -subject 2>/dev/null | grep -q "Developer ID Application"; then
  warn "That certificate is not a 'Developer ID Application' certificate:"
  openssl x509 -inform DER -in "$CER_PATH" -noout -subject 2>/dev/null | sed 's/^/    /'
  confirm "Continue anyway?" || exit 1
fi
printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$(openssl x509 -inform DER -in "$CER_PATH" -noout -subject | sed 's/.*CN=//; s/,.*//')"
pause

# ──────────────────────────────────────────────────────────────────────────
stage "Package the certificate as a .p12"
say "CI imports a .p12 holding the private key, your certificate, and Apple's"
say "intermediate. Omitting the intermediate is the classic cause of"
say "'errSecInternalComponent' at codesign time on a clean runner."
printf '\n'
openssl x509 -inform DER -in "$CER_PATH" -out "$WORK/developer-id.pem" 2>/dev/null
curl -fsSL -o "$WORK/DeveloperIDG2CA.cer" "https://www.apple.com/certificateauthority/DeveloperIDG2CA.cer"
openssl x509 -inform DER -in "$WORK/DeveloperIDG2CA.cer" -out "$WORK/intermediate.pem" 2>/dev/null
printf '  %s✓%s fetched the Apple Developer ID G2 intermediate\n' "$GREEN" "$RESET"

P12_PASSWORD="$(openssl rand -base64 24 | tr -d '\n')"
# OpenSSL 3 defaults to AES-256, which macOS `security import` rejects; -legacy
# restores the 3DES/SHA-1 encoding the Security framework expects.
LEGACY=()
if openssl pkcs12 -help 2>&1 | grep -q -- '-legacy'; then LEGACY=(-legacy); fi
openssl pkcs12 -export "${LEGACY[@]}" \
  -inkey "$WORK/developer-id.key" \
  -in "$WORK/developer-id.pem" \
  -certfile "$WORK/intermediate.pem" \
  -name "Developer ID Application" \
  -out "$WORK/developer-id.p12" \
  -passout pass:"$P12_PASSWORD" 2>/dev/null
chmod 600 "$WORK/developer-id.p12"
printf '  %s✓%s built %s\n' "$GREEN" "$RESET" "$WORK/developer-id.p12"

set_secret DEVELOPER_ID_P12 "$(b64 "$WORK/developer-id.p12")"
set_secret DEVELOPER_ID_P12_PASSWORD "$P12_PASSWORD"
note "The .p12 password is random and stored only as a GitHub secret."

# ──────────────────────────────────────────────────────────────────────────
stage "App Store Connect API key (notarization)"
say "notarytool authenticates with an API key rather than your Apple ID, so CI"
say "never handles your password and the key can be revoked on its own."
open_url "https://appstoreconnect.apple.com/access/integrations/api"
step "Open the 'Team Keys' tab, then click + to generate a key."
step "Name it something like 'Lumeshot notarization'."
step "Set Access to 'Developer' — that is sufficient for notarytool."
step "Click Generate, then Download the .p8."
printf '\n'
warn "Apple lets you download the .p8 exactly once. Keep it somewhere safe."
printf '\n'
step "The Issuer ID is above the key list; the Key ID is on the key's row."
ask ASC_KEY_ID "Paste the Key ID (10 chars):"
ask ASC_ISSUER_ID "Paste the Issuer ID (a UUID):"
ask P8_PATH "Full path to the downloaded .p8:"
P8_PATH="${P8_PATH/#\~/$HOME}"
[ -f "$P8_PATH" ] || { warn "No file at $P8_PATH"; exit 1; }
grep -q "PRIVATE KEY" "$P8_PATH" || { warn "$P8_PATH does not look like a .p8 private key"; exit 1; }
write_env ASC_KEY_ID "$ASC_KEY_ID"
write_env ASC_ISSUER_ID "$ASC_ISSUER_ID"
set_secret ASC_KEY_ID "$ASC_KEY_ID"
set_secret ASC_ISSUER_ID "$ASC_ISSUER_ID"
set_secret ASC_KEY_P8 "$(b64 "$P8_PATH")"

# ──────────────────────────────────────────────────────────────────────────
stage "Verify"
say "The release workflow turns signing on only when both DEVELOPER_ID_P12 and"
say "ASC_KEY_P8 are present, so a missing secret silently ships an unsigned dmg."
printf '\n'
EXPECTED="DEVELOPER_ID_P12 DEVELOPER_ID_P12_PASSWORD ASC_KEY_P8 ASC_KEY_ID ASC_ISSUER_ID TEAM_ID"
PRESENT="$(gh secret list --json name -q '.[].name' 2>/dev/null || true)"
ALL_OK=1
for name in $EXPECTED; do
  if printf '%s\n' "$PRESENT" | grep -qx "$name"; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$name"
  else
    printf '  %s✗ %s missing%s\n' "$RED" "$name" "$RESET"; ALL_OK=0
  fi
done
printf '\n'
if [ "$ALL_OK" -eq 1 ]; then
  say "All six secrets are set. Cut a signed release with:"
  printf '\n      %sgit tag v0.2.0 && git push origin v0.2.0%s\n\n' "$BOLD" "$RESET"
  say "Then verify the published dmg per docs/smoke-signing.md."
else
  warn "Set the missing secrets before tagging, or the release will be unsigned."
fi
if confirm "Delete the local working files (.key/.csr/.p12/.pem) now that they're uploaded?"; then
  rm -rf "$WORK"
  printf '  %s✓%s removed %s\n' "$GREEN" "$RESET" "$WORK"
  note "Keep your .cer and .p8 backups elsewhere — Apple will not re-issue the .p8."
else
  warn "Sensitive material remains in $WORK — it is mode 700, but delete it when done."
fi

finish
